# NUMPY

In [1]:
import numpy 
arr = numpy.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


#### alias as np

In [2]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
print(arr)
print(type(arr))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


## 0,1,2,3 - D ARRAY

In [5]:
import numpy as np
arr0 = np.array(99)
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr3 = np.array([[[1,2,3,4,5],[6,7,8,9,10]]])

print(arr0 ,"dim : ",arr0.ndim)

print(arr1 ,"dim : ",arr1.ndim)

print(arr2 ,"dim : ",arr2.ndim)

print(arr3 ,"dim : ",arr3.ndim)


99 dim :  0
[1 2 3 4 5] dim :  1
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] dim :  2
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]] dim :  3


#### check dimension

In [6]:
print(arr0.ndim)

0


## Higher dimension

In [15]:
import numpy as np
array_temp = np.array([1,2,3,4,5],ndmin=5)
print(array_temp)
print("Dimension of the array :")
print(array_temp.ndim)

[[[[[1 2 3 4 5]]]]]
Dimension of the array :
5


In [13]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)


[[[[[1 2 3 4]]]]]
number of dimensions : 5


## Access array elements

In [17]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
print(arr[0])

1


In [20]:
print(arr[1])                                                        # 1D ARRAY


2


In [19]:
print(arr[1]+arr[3])                                                 # 1D ARRAY

6


In [22]:
import numpy as np                                                   # 2D ARRAY
arr = np.array([[1,2,3,4,5,6],[9,6,0,3,2,9]])
print(arr[0,3])

4


In [23]:
arr = np.array([[1,2],[9,6],[5,4],[3,1]])                            # 2D ARRAY
print(arr[2,1])

4


In [27]:
arr = np.array([[[1,2,3,4,5,6],[9,6,0,3,2,9]]])
print(arr[0,3,1])

IndexError: index 3 is out of bounds for axis 1 with size 2